apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: space1
subjects:
  - kind: ServiceAccount
    name: service
    apiGroup: ""
roleRef:
  kind: Role
  name: role
  apiGroup: ""