apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding2
  namespace: space2
subjects:
  - kind: ServiceAccount
    name: service
    namespace: space1
    apiGroup: ""
roleRef:
  kind: Role
  name: role2
  apiGroup: ""